import { addCartItem, currentUser, getCart, toggleFavorite } from "./supabase.js?v=20260706-2";

const referenceProducts = [
  { id:"31d03601-5ff1-4b36-8825-5884c00d3332", name:"Ətir", brand:"Brend", price:100, old:110, image:"https://ibhmwwdrzgjgwfrvpjht.supabase.co/storage/v1/object/public/product-images/d39654de-946a-4352-b1f1-77b7facd2705/986c0fbc-169b-49a9-b6f1-f4a79a844db9.jpg", rating:"0.0", reviews:0 },
  { id:"118306a5-3867-42db-a025-170f52e786f7", name:"italya mebel", brand:"avilla", price:1500, old:1800, image:"https://ibhmwwdrzgjgwfrvpjht.supabase.co/storage/v1/object/public/product-images/d39654de-946a-4352-b1f1-77b7facd2705/cbb4919c-9264-42fb-88cb-3351e81d812c.jpg", rating:"5.0", reviews:2 },
  { id:"e6635adc-e394-485f-b999-a7ee263760cd", name:"Mopet", brand:"Bmv", price:1000, old:null, image:"https://ibhmwwdrzgjgwfrvpjht.supabase.co/storage/v1/object/public/product-images/d39654de-946a-4352-b1f1-77b7facd2705/721da7d9-71c3-43fb-9cc2-7e34fded753b.jpg", rating:"0.0", reviews:0 },
  { id:"9dfcd652-cfd9-4e1e-8496-8a11934f4fb2", name:"Xiaomi", brand:"Redmı", price:800, old:null, image:"https://ibhmwwdrzgjgwfrvpjht.supabase.co/storage/v1/object/public/product-images/d39654de-946a-4352-b1f1-77b7facd2705/b43b3238-5324-4b67-87e4-fa2ad6232ce7.jpg", rating:"5.0", reviews:1 },
  { id:"af318359-3b26-4080-ac5b-67c4518d3ac8", name:"kofe", brand:"", price:100, old:null, image:"https://ibhmwwdrzgjgwfrvpjht.supabase.co/storage/v1/object/public/product-images/d39654de-946a-4352-b1f1-77b7facd2705/d58b87e3-b1b5-4084-b21f-3545cc816552.jpg", rating:"0.0", reviews:0 },
  { id:"69fbe1c2-af49-4b0e-a4f6-c6d4ec75fb57", name:"Portable", brand:"", price:30, old:null, image:"https://ibhmwwdrzgjgwfrvpjht.supabase.co/storage/v1/object/public/product-images/ab3f5c02-b3d9-461c-ba4a-f3b22c627bfb/3a362ccf-4a19-4f86-8e4e-333ff846e46c.jpg", rating:"0.0", reviews:0 }
];
const egshopCategories=[["📱","Elektronika"],["👗","Qadın geyimləri"],["👔","Kişi geyimləri"],["👶","Uşaq və körpə"],["👟","Ayaqqabı"],["💄","Gözəllik və baxım"],["🏠","Ev və mətbəx"],["🛏️","Ev tekstili"],["🚗","Avtomobil"],["🔧","Tikinti və təmir"],["🌳","Bağ və həyət"],["⚽","İdman və istirahət"]];
const egshopSubcategories=["Smartfonlar","Telefon aksesuarları","Noutbuklar","Planşetlər","Stolüstü kompüterlər","Monitorlar"];
function discount(p){return p.old?Math.round((1-p.price/p.old)*100):0}
function card(p){const d=discount(p);return `<article class="lv-card" data-product-id="${p.id}" data-product-name="${p.name.toLocaleLowerCase("az-AZ")}"><div class="lv-card-media">${d?`<span class="lv-discount">-${d}%</span>`:""}<button class="lv-heart" type="button" aria-label="Sevimlilərə əlavə et">♡</button><img src="${p.image}" alt="${p.name}" loading="lazy"></div><div class="lv-card-body"><div class="lv-price"><strong>${p.price} ₼</strong>${p.old?`<del>${p.old} ₼</del>`:""}</div><small>${p.brand||"&nbsp;"}</small><h3>${p.name}</h3><div class="lv-rating"><span>★</span> ${p.rating} <i>· ${p.reviews}</i></div><button class="lv-cart" type="button">Səbətə at</button></div></article>`}
function productSection(title,products,className="",kicker=""){return `<section class="lv-product-section ${className}"><div class="lv-section-heading"><div>${kicker?`<span class="lv-kicker">${kicker}</span>`:""}<h2>${title}</h2></div><button type="button" class="lv-all">Hamısına bax →</button></div><div class="lv-products">${products.map(card).join("")}</div></section>`}
function buildEgshopHome(main){if(main.dataset.egshopHome)return;main.dataset.egshopHome="true";const dialogs=Array.from(main.querySelectorAll("dialog"));const quick=main.querySelector(".quick-links");main.innerHTML=`<h1 class="sr-only">EG Shop — Azərbaycanın onlayn marketi</h1>${quick?quick.outerHTML:""}<section class="lv-category-area"><div class="lv-scroll lv-categories">${egshopCategories.map(([i,n],x)=>`<button type="button" class="${x===0?"active":""}"><span>${i}</span>${n}</button>`).join("")}</div><div class="lv-section-heading lv-subheading"><h2>Önə çıxan kateqoriyalar</h2><button type="button">Hamısı ›</button></div><div class="lv-scroll lv-subcategories">${egshopSubcategories.map(n=>`<button type="button"><span>📱</span>${n}</button>`).join("")}</div></section><section class="lv-ad"><video autoplay muted loop playsinline preload="metadata" src="https://ibhmwwdrzgjgwfrvpjht.supabase.co/storage/v1/object/public/product-images/12ea4064-c75b-46f7-be42-a9242b61737e/banner-video-1782387703134.mp4"></video><span class="lv-ad-label">REKLAM</span><strong>Mmm</strong></section>${productSection("🎁 Uduşlu Məhsullar",[referenceProducts[0]],"lv-win","🎁 UDUŞ")}${productSection("Endirimli qiymətlər",[referenceProducts[1],referenceProducts[2],referenceProducts[0]],"lv-sale","70% ENDİRİM")}${productSection("Trend məhsullar",[referenceProducts[1],referenceProducts[3],referenceProducts[3],referenceProducts[3],referenceProducts[2],referenceProducts[4]],"","Hamı baxır")}${productSection("Sizin üçün",[referenceProducts[0],referenceProducts[4],referenceProducts[2],referenceProducts[1],referenceProducts[5],referenceProducts[3],referenceProducts[3],referenceProducts[3]])}`;dialogs.forEach(d=>main.append(d));alignNavigation();bindEgshopHome(main)}
function alignNavigation(){const labels=[["⌂","Ana səhifə"],["▦","Kataloq"],["🛒","Səbət"],["♡","Sevimli"],["♙","Kabinet"]];document.querySelectorAll(".mobile-nav button").forEach((item,index)=>{if(!labels[index])return;const badge=item.querySelector("i")?.outerHTML||"";item.innerHTML=`<span>${labels[index][0]}</span>${labels[index][1]}${badge}`})}
function notify(message){const toast=document.querySelector("#toast");if(!toast)return;toast.textContent=message;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),2000)}
async function refreshCartCount(){const items=await getCart();const count=items.reduce((sum,item)=>sum+Number(item.quantity||0),0);document.querySelectorAll("#cartCount,#mobileCartCount").forEach(item=>item.textContent=String(count))}
function bindEgshopHome(main){main.querySelectorAll(".lv-categories button").forEach(b=>b.addEventListener("click",()=>main.querySelectorAll(".lv-categories button").forEach(i=>i.classList.toggle("active",i===b))));main.querySelectorAll(".lv-cart").forEach(b=>b.addEventListener("click",async()=>{if(!currentUser())return document.querySelector("[data-auth]")?.click();b.disabled=true;try{await addCartItem(b.closest(".lv-card").dataset.productId);await refreshCartCount();notify("Məhsul səbətə əlavə edildi")}catch(e){notify(e.message)}finally{b.disabled=false}}));main.querySelectorAll(".lv-heart").forEach(b=>b.addEventListener("click",async()=>{if(!currentUser())return document.querySelector("[data-auth]")?.click();try{const added=await toggleFavorite(b.closest(".lv-card").dataset.productId);b.textContent=added?"♥":"♡";b.classList.toggle("active",added);notify(added?"Sevimlilərə əlavə edildi":"Sevimlilərdən silindi")}catch(e){notify(e.message)}}));main.querySelectorAll(".lv-all").forEach(b=>b.addEventListener("click",()=>b.closest(".lv-product-section")?.querySelector(".lv-products")?.scrollTo({left:9999,behavior:"smooth"})));const search=document.querySelector("#searchInput");search?.addEventListener("input",()=>{const q=search.value.trim().toLocaleLowerCase("az-AZ");main.querySelectorAll(".lv-card").forEach(i=>i.hidden=Boolean(q)&&!i.dataset.productName.includes(q))})}
function startEgshopHome(){const app=document.querySelector("#app");if(!app)return;const apply=()=>{const main=app.querySelector("main");if(!main)return false;buildEgshopHome(main);return true};if(apply())return;const observer=new MutationObserver(()=>{if(apply())observer.disconnect()});observer.observe(app,{childList:true,subtree:true})}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",startEgshopHome);else startEgshopHome();
