-- Complete the RU/EN labels for the marketplace taxonomy.
-- Existing non-empty translations remain authoritative.
with translations(slug, name_ru, name_en) as (
  values
  ('elektronika', 'Электроника', 'Electronics'),
  ('qadin-geyimleri', 'Женская одежда', 'Women''s clothing'),
  ('kisi-geyimleri', 'Мужская одежда', 'Men''s clothing'),
  ('usaq-ve-korpe', 'Детские товары', 'Kids & baby'),
  ('ayaqqabi', 'Обувь', 'Shoes'),
  ('gozellik-ve-baxim', 'Красота и уход', 'Beauty & care'),
  ('ev-ve-metbex', 'Дом и кухня', 'Home & kitchen'),
  ('ev-tekstili', 'Домашний текстиль', 'Home textiles'),
  ('avtomobil', 'Автомобиль', 'Automotive'),
  ('tikinti-ve-temir', 'Строительство и ремонт', 'Construction & repair'),
  ('bag-ve-heyet', 'Сад и двор', 'Garden & yard'),
  ('idman-ve-istirahet', 'Спорт и отдых', 'Sports & leisure'),
  ('heyvan-mehsullari', 'Товары для животных', 'Pet products'),
  ('kitablar-ve-ofis', 'Книги и офис', 'Books & office'),
  ('erzaq-mehsullari', 'Продукты питания', 'Groceries'),
  ('saglamliq', 'Здоровье', 'Health'),
  ('hediyye-ve-suvenir', 'Подарки и сувениры', 'Gifts & souvenirs'),
  ('zergerlik-ve-saatlar', 'Украшения и часы', 'Jewelry & watches'),
  ('oyun-ve-hobbi', 'Игры и хобби', 'Games & hobby'),
  ('cantalar-ve-aksesuarlar', 'Сумки и аксессуары', 'Bags & accessories'),
  ('avtomobil-avtomobil-aksesuarlari', 'Автоаксессуары', 'Car accessories'),
  ('bag-ve-heyet-bag-aletleri', 'Садовые инструменты', 'Garden tools'),
  ('kitablar-ve-ofis-bedii-edebiyyat', 'Художественная литература', 'Fiction'),
  ('erzaq-mehsullari-cay-ve-qehve', 'Чай и кофе', 'Tea & coffee'),
  ('gozellik-ve-baxim-dekorativ-kosmetika', 'Декоративная косметика', 'Makeup'),
  ('qadin-geyimleri-donlar', 'Платья', 'Dresses'),
  ('tikinti-ve-temir-el-aletleri', 'Ручные инструменты', 'Hand tools'),
  ('idman-ve-istirahet-fitness-levazimatlari', 'Товары для фитнеса', 'Fitness equipment'),
  ('hediyye-ve-suvenir-hediyye-destleri', 'Подарочные наборы', 'Gift sets'),
  ('heyvan-mehsullari-it-yemleri', 'Корма для собак', 'Dog food'),
  ('usaq-ve-korpe-korpe-geyimleri', 'Одежда для малышей', 'Baby clothing'),
  ('kisi-geyimleri-koynekler', 'Рубашки', 'Shirts'),
  ('oyun-ve-hobbi-playstation-oyunlari', 'Игры PlayStation', 'PlayStation games'),
  ('ev-ve-metbex-qab-qacaq', 'Посуда', 'Tableware'),
  ('ayaqqabi-qadin-ayaqqabilari', 'Женская обувь', 'Women''s shoes'),
  ('cantalar-ve-aksesuarlar-qadin-cantalari', 'Женские сумки', 'Women''s bags'),
  ('elektronika-smartfonlar', 'Смартфоны', 'Smartphones'),
  ('zergerlik-ve-saatlar-uzukler', 'Кольца', 'Rings'),
  ('saglamliq-vitaminler', 'Витамины', 'Vitamins'),
  ('ev-tekstili-yataq-destleri', 'Постельные комплекты', 'Bedding sets'),
  ('saglamliq-bae-ve-bioloji-aktiv', 'БАДы и биологически активные добавки', 'Supplements & bioactive'),
  ('qadin-geyimleri-bluzlar-ve-koynekler', 'Блузки и рубашки', 'Blouses & shirts'),
  ('zergerlik-ve-saatlar-boyunbagilar', 'Ожерелья', 'Necklaces'),
  ('ev-ve-metbex-cengel-bicaq-destleri', 'Столовые приборы', 'Cutlery sets'),
  ('tikinti-ve-temir-elektrik-aletleri', 'Электроинструменты', 'Power tools'),
  ('kisi-geyimleri-futbolkalar', 'Футболки', 'T-shirts'),
  ('hediyye-ve-suvenir-hediyye-qutulari', 'Подарочные коробки', 'Gift boxes'),
  ('ayaqqabi-kisi-ayaqqabilari', 'Мужская обувь', 'Men''s shoes'),
  ('cantalar-ve-aksesuarlar-kisi-cantalari', 'Мужские сумки', 'Men''s bags'),
  ('heyvan-mehsullari-pisik-yemleri', 'Корма для кошек', 'Cat food'),
  ('erzaq-mehsullari-sirniyyat', 'Сладости', 'Sweets'),
  ('elektronika-telefon-aksesuarlari', 'Аксессуары для телефонов', 'Phone accessories'),
  ('bag-ve-heyet-toxumlar-ve-soganaqlar', 'Семена и луковицы', 'Seeds & bulbs'),
  ('idman-ve-istirahet-trenajorlar', 'Тренажёры', 'Exercise machines'),
  ('usaq-ve-korpe-usaq-geyimleri', 'Детская одежда', 'Kids clothing'),
  ('kitablar-ve-ofis-usaq-kitablari', 'Детские книги', 'Children’s books'),
  ('gozellik-ve-baxim-uz-baximi', 'Уход за лицом', 'Face care'),
  ('oyun-ve-hobbi-xbox-oyunlari', 'Игры Xbox', 'Xbox games'),
  ('avtomobil-yag-ve-mayeler', 'Масла и жидкости', 'Oils & fluids'),
  ('ev-tekstili-yorgan-ve-yastiqlar', 'Одеяла и подушки', 'Blankets & pillows'),
  ('ev-tekstili-adyallar-ve-pledler', 'Одеяла и пледы', 'Throws & blankets'),
  ('cantalar-ve-aksesuarlar-bel-cantalari', 'Поясные сумки', 'Waist bags'),
  ('bag-ve-heyet-bitkiler-ve-guller', 'Растения и цветы', 'Plants & flowers'),
  ('kitablar-ve-ofis-derslikler', 'Учебники', 'Textbooks'),
  ('oyun-ve-hobbi-nintendo-oyunlari', 'Игры Nintendo', 'Nintendo games'),
  ('elektronika-noutbuklar', 'Ноутбуки', 'Laptops'),
  ('tikinti-ve-temir-olcu-cihazlari', 'Измерительные приборы', 'Measuring tools'),
  ('heyvan-mehsullari-qus-yemleri', 'Корма для птиц', 'Bird food'),
  ('gozellik-ve-baxim-sac-baximi', 'Уход за волосами', 'Hair care'),
  ('kisi-geyimleri-salvarlar', 'Брюки', 'Pants'),
  ('avtomobil-sinler-ve-diskler', 'Шины и диски', 'Tires & rims'),
  ('zergerlik-ve-saatlar-sirgalar', 'Серьги', 'Earrings'),
  ('erzaq-mehsullari-sokolad', 'Шоколад', 'Chocolate'),
  ('hediyye-ve-suvenir-suvenirler', 'Сувениры', 'Souvenirs'),
  ('ev-ve-metbex-tavalar-ve-qazanlar', 'Сковороды и кастрюли', 'Pans & pots'),
  ('saglamliq-tibbi-cihazlar', 'Медицинские приборы', 'Medical devices'),
  ('ayaqqabi-usaq-ayaqqabilari', 'Детская обувь', 'Kids shoes'),
  ('usaq-ve-korpe-usaq-ayaqqabilari', 'Детская обувь', 'Kids shoes'),
  ('idman-ve-istirahet-velosipedler', 'Велосипеды', 'Bicycles'),
  ('qadin-geyimleri-yubkalar', 'Юбки', 'Skirts'),
  ('heyvan-mehsullari-akvarium-levazimatlari', 'Аквариумные принадлежности', 'Aquarium supplies'),
  ('hediyye-ve-suvenir-bayram-mehsullari', 'Праздничные товары', 'Holiday products'),
  ('gozellik-ve-baxim-beden-baximi', 'Уход за телом', 'Body care'),
  ('ev-ve-metbex-bicaqlar', 'Ножи', 'Knives'),
  ('kisi-geyimleri-cinsler', 'Джинсы', 'Jeans'),
  ('cantalar-ve-aksesuarlar-ciyin-cantalari', 'Сумки через плечо', 'Shoulder bags'),
  ('ev-tekstili-desmal-ve-hamam-destleri', 'Полотенца и банные наборы', 'Towels & bath sets'),
  ('avtomobil-ehtiyat-hisseleri', 'Запчасти', 'Spare parts'),
  ('bag-ve-heyet-gubreler', 'Удобрения', 'Fertilizers'),
  ('ayaqqabi-idman-ayaqqabilari', 'Спортивная обувь', 'Sports shoes'),
  ('kitablar-ve-ofis-is-ve-biznes', 'Работа и бизнес', 'Work & business'),
  ('usaq-ve-korpe-oyuncaqlar', 'Игрушки', 'Toys'),
  ('oyun-ve-hobbi-pc-oyunlari', 'Игры для ПК', 'PC games'),
  ('erzaq-mehsullari-pecenye-ve-vafli', 'Печенье и вафли', 'Cookies & waffles'),
  ('elektronika-plansetler', 'Планшеты', 'Tablets'),
  ('zergerlik-ve-saatlar-qolbaqlar', 'Браслеты', 'Bracelets'),
  ('qadin-geyimleri-salvarlar', 'Брюки', 'Pants'),
  ('idman-ve-istirahet-samokatlar', 'Самокаты', 'Scooters'),
  ('tikinti-ve-temir-santexnika', 'Сантехника', 'Plumbing'),
  ('saglamliq-tonometrler', 'Тонометры', 'Blood pressure monitors'),
  ('avtomobil-avtomobil-kimyasi', 'Автохимия', 'Car care chemicals'),
  ('qadin-geyimleri-cinsler', 'Джинсы', 'Jeans'),
  ('kitablar-ve-ofis-defterxana-levazimatlari', 'Канцелярские товары', 'Stationery'),
  ('tikinti-ve-temir-elektrik-materiallari', 'Электроматериалы', 'Electrical materials'),
  ('gozellik-ve-baxim-etirler', 'Парфюмерия', 'Perfumes'),
  ('cantalar-ve-aksesuarlar-kemerler', 'Ремни', 'Belts'),
  ('heyvan-mehsullari-heyvan-aksesuarlari', 'Аксессуары для животных', 'Pet accessories'),
  ('ev-ve-metbex-kicik-meiset-texnikasi', 'Мелкая бытовая техника', 'Small appliances'),
  ('zergerlik-ve-saatlar-kisi-saatlari', 'Мужские часы', 'Men''s watches'),
  ('idman-ve-istirahet-komanda-idmani', 'Командные виды спорта', 'Team sports'),
  ('erzaq-mehsullari-konservler', 'Консервы', 'Canned food'),
  ('usaq-ve-korpe-konstruktorlar', 'Конструкторы', 'Building sets'),
  ('ayaqqabi-krossovkalar', 'Кроссовки', 'Sneakers'),
  ('ev-tekstili-perdeler', 'Шторы', 'Curtains'),
  ('cantalar-ve-aksesuarlar-seyahet-cantalari', 'Дорожные сумки', 'Travel bags'),
  ('kisi-geyimleri-sortlar', 'Шорты', 'Shorts'),
  ('elektronika-stolustu-komputerler', 'Настольные компьютеры', 'Desktop computers'),
  ('oyun-ve-hobbi-stolustu-oyunlar', 'Настольные игры', 'Board games'),
  ('bag-ve-heyet-suvarma-sistemleri', 'Системы полива', 'Watering systems'),
  ('saglamliq-termometrler', 'Термометры', 'Thermometers'),
  ('hediyye-ve-suvenir-yeni-il-mehsullari', 'Новогодние товары', 'New Year products'),
  ('bag-ve-heyet-bag-mebeli', 'Садовая мебель', 'Garden furniture'),
  ('tikinti-ve-temir-boya-ve-laklar', 'Краски и лаки', 'Paints & varnishes'),
  ('ev-ve-metbex-boyuk-meiset-texnikasi', 'Крупная бытовая техника', 'Large appliances'),
  ('cantalar-ve-aksesuarlar-camadanlar', 'Чемоданы', 'Suitcases'),
  ('ayaqqabi-cekmeler', 'Сапоги и ботинки', 'Boots'),
  ('erzaq-mehsullari-ickiler', 'Напитки', 'Drinks'),
  ('saglamliq-inhalyatorlar', 'Ингаляторы', 'Inhalers'),
  ('usaq-ve-korpe-korpe-arabalari', 'Коляски', 'Strollers'),
  ('kisi-geyimleri-kostyumlar', 'Костюмы', 'Suits'),
  ('gozellik-ve-baxim-manikur-ve-pedikur', 'Маникюр и педикюр', 'Manicure & pedicure'),
  ('elektronika-monitorlar', 'Мониторы', 'Monitors'),
  ('oyun-ve-hobbi-pazllar', 'Пазлы', 'Puzzles'),
  ('qadin-geyimleri-pencekler', 'Жакеты', 'Blazers'),
  ('zergerlik-ve-saatlar-qadin-saatlari', 'Женские часы', 'Women''s watches'),
  ('heyvan-mehsullari-qefes-ve-dasiyicilar', 'Клетки и переноски', 'Cages & carriers'),
  ('avtomobil-salon-aksesuarlari', 'Аксессуары для салона', 'Interior accessories'),
  ('hediyye-ve-suvenir-sarlar', 'Шары', 'Balloons'),
  ('idman-ve-istirahet-uzguculuk', 'Плавание', 'Swimming'),
  ('ev-tekstili-xalcalar-ve-xali', 'Ковры и паласы', 'Carpets & rugs'),
  ('kitablar-ve-ofis-yazi-vasiteleri', 'Письменные принадлежности', 'Writing supplies'),
  ('usaq-ve-korpe-avtokreslolari', 'Автокресла', 'Car seats'),
  ('avtomobil-avtomobil-aletleri', 'Автоинструменты', 'Car tools'),
  ('saglamliq-bandaj-ve-ortez', 'Бандажи и ортезы', 'Bandages & orthoses'),
  ('heyvan-mehsullari-gigiyena-vasiteleri', 'Средства гигиены', 'Hygiene products'),
  ('kitablar-ve-ofis-kagiz-mehsullari', 'Бумажная продукция', 'Paper products'),
  ('gozellik-ve-baxim-kisi-baximi', 'Мужской уход', 'Men''s care'),
  ('elektronika-klaviatura-ve-mauslar', 'Клавиатуры и мыши', 'Keyboards & mice'),
  ('bag-ve-heyet-mangal-ve-barbeku', 'Мангалы и барбекю', 'Grills & BBQ'),
  ('qadin-geyimleri-paltolar-ve-kurkler', 'Пальто и шубы', 'Coats & fur coats'),
  ('kisi-geyimleri-pencekler', 'Пиджаки', 'Blazers'),
  ('cantalar-ve-aksesuarlar-pulqabilar', 'Кошельки', 'Wallets'),
  ('oyun-ve-hobbi-radioidareli-modeller', 'Радиоуправляемые модели', 'RC models'),
  ('ayaqqabi-sandallar', 'Сандалии', 'Sandals'),
  ('ev-tekstili-sufreler', 'Скатерти', 'Tablecloths'),
  ('hediyye-ve-suvenir-suni-guller', 'Искусственные цветы', 'Artificial flowers'),
  ('tikinti-ve-temir-tikinti-materiallari', 'Строительные материалы', 'Building materials'),
  ('ev-ve-metbex-tozsoranlar', 'Пылесосы', 'Vacuum cleaners'),
  ('idman-ve-istirahet-turizm-ve-kemping', 'Туризм и кемпинг', 'Tourism & camping'),
  ('erzaq-mehsullari-usaq-qidalari', 'Детское питание', 'Baby food'),
  ('zergerlik-ve-saatlar-usaq-saatlari', 'Детские часы', 'Kids watches'),
  ('hediyye-ve-suvenir-acarliqlar', 'Брелоки', 'Keychains'),
  ('zergerlik-ve-saatlar-bijuteriya', 'Бижутерия', 'Fashion jewelry'),
  ('ev-tekstili-divan-ortukleri', 'Чехлы для диванов', 'Sofa covers'),
  ('saglamliq-gigiyena-mehsullari', 'Гигиенические товары', 'Hygiene products'),
  ('bag-ve-heyet-hovuzlar', 'Бассейны', 'Pools'),
  ('ayaqqabi-klassik-ayaqqabilar', 'Классическая обувь', 'Classic shoes'),
  ('oyun-ve-hobbi-musiqi-aletleri', 'Музыкальные инструменты', 'Musical instruments'),
  ('kitablar-ve-ofis-ofis-mebeli', 'Офисная мебель', 'Office furniture'),
  ('idman-ve-istirahet-ovculuq-ve-baliqciliq', 'Охота и рыбалка', 'Hunting & fishing'),
  ('heyvan-mehsullari-oyuncaqlar', 'Игрушки', 'Toys'),
  ('kisi-geyimleri-paltolar-ve-godekceler', 'Пальто и куртки', 'Coats & jackets'),
  ('tikinti-ve-temir-qapi-ve-qifillar', 'Двери и замки', 'Doors & locks'),
  ('erzaq-mehsullari-quru-meyve-ve-qoz', 'Сухофрукты и орехи', 'Dried fruits & nuts'),
  ('gozellik-ve-baxim-sac-qurutma-ve-duzeltme', 'Сушка и укладка волос', 'Hair dryers & styling'),
  ('qadin-geyimleri-trikotaj', 'Трикотаж', 'Knitwear'),
  ('usaq-ve-korpe-usaq-qidalari', 'Детское питание', 'Baby food'),
  ('ev-ve-metbex-utuler', 'Утюги', 'Irons'),
  ('avtomobil-videoqeydiyyatcilar', 'Видеорегистраторы', 'Dash cameras'),
  ('elektronika-yaddas-ve-diskler', 'Память и диски', 'Memory & drives'),
  ('qadin-geyimleri-alt-paltarlari', 'Нижнее бельё', 'Underwear'),
  ('avtomobil-avtomobil-ses-sistemleri', 'Автомобильные аудиосистемы', 'Car audio systems'),
  ('bag-ve-heyet-cemen-bicen', 'Газонокосилки', 'Lawn mowers'),
  ('tikinti-ve-temir-doseme-materiallari', 'Напольные покрытия', 'Flooring materials'),
  ('gozellik-ve-baxim-epilyasiya-cihazlari', 'Эпиляторы', 'Hair removal devices'),
  ('ayaqqabi-ev-ayaqqabilari', 'Домашняя обувь', 'Home shoes'),
  ('erzaq-mehsullari-edviyyatlar', 'Специи', 'Spices'),
  ('oyun-ve-hobbi-el-isi-ve-yaradiciliq', 'Рукоделие и творчество', 'Handmade & creativity'),
  ('saglamliq-ilk-yardim', 'Первая помощь', 'First aid'),
  ('ev-ve-metbex-metbex-aksesuarlari', 'Кухонные аксессуары', 'Kitchen accessories'),
  ('usaq-ve-korpe-pampers-ve-gigiyena', 'Подгузники и гигиена', 'Diapers & hygiene'),
  ('kitablar-ve-ofis-printer-kagizlari', 'Бумага для принтера', 'Printer paper'),
  ('elektronika-printerler-ve-skanerler', 'Принтеры и сканеры', 'Printers & scanners'),
  ('idman-ve-istirahet-qis-idmani', 'Зимние виды спорта', 'Winter sports'),
  ('zergerlik-ve-saatlar-qizil-memulatlar', 'Золотые изделия', 'Gold jewelry'),
  ('cantalar-ve-aksesuarlar-serfler-ve-sallar', 'Шарфы и шали', 'Scarves & shawls'),
  ('kisi-geyimleri-trikotaj', 'Трикотаж', 'Knitwear'),
  ('gozellik-ve-baxim-agiz-gigiyenasi', 'Гигиена полости рта', 'Oral hygiene'),
  ('kisi-geyimleri-alt-paltarlari', 'Нижнее бельё', 'Underwear'),
  ('tikinti-ve-temir-divar-kagizlari', 'Обои', 'Wallpapers'),
  ('idman-ve-istirahet-doyus-idmani', 'Боевые виды спорта', 'Martial arts'),
  ('zergerlik-ve-saatlar-gumus-memulatlar', 'Серебряные изделия', 'Silver jewelry'),
  ('oyun-ve-hobbi-kolleksiya', 'Коллекционирование', 'Collectibles'),
  ('usaq-ve-korpe-mektebli-levazimatlari', 'Школьные принадлежности', 'School supplies'),
  ('avtomobil-motosiklet-aksesuarlari', 'Мотоаксессуары', 'Motorcycle accessories'),
  ('saglamliq-optika-ve-eynekler', 'Оптика и очки', 'Optics & glasses'),
  ('cantalar-ve-aksesuarlar-papaqlar', 'Шапки', 'Hats'),
  ('qadin-geyimleri-pijamalar', 'Пижамы', 'Pajamas'),
  ('ayaqqabi-rezin-cekmeler', 'Резиновые сапоги', 'Rubber boots'),
  ('erzaq-mehsullari-saglam-qidalanma', 'Здоровое питание', 'Healthy food'),
  ('ev-ve-metbex-saxlama-qablari', 'Контейнеры для хранения', 'Storage containers'),
  ('elektronika-sebeke-avadanligi', 'Сетевое оборудование', 'Network equipment'),
  ('cantalar-ve-aksesuarlar-eynekler', 'Очки', 'Glasses'),
  ('kisi-geyimleri-idman-geyimleri', 'Спортивная одежда', 'Sportswear'),
  ('qadin-geyimleri-idman-geyimleri', 'Спортивная одежда', 'Sportswear'),
  ('tikinti-ve-temir-is-geyimleri-ve-qoruyucu', 'Рабочая одежда и защита', 'Workwear & protection'),
  ('ev-ve-metbex-mebel', 'Мебель', 'Furniture'),
  ('gozellik-ve-baxim-professional-vasiteler', 'Профессиональные средства', 'Professional products'),
  ('elektronika-televizorlar', 'Телевизоры', 'TVs'),
  ('usaq-ve-korpe-usaq-mebeli', 'Детская мебель', 'Kids furniture'),
  ('idman-ve-istirahet-yoga-ve-pilates', 'Йога и пилатес', 'Yoga & pilates'),
  ('elektronika-audio-sistemler', 'Аудиосистемы', 'Audio systems'),
  ('cantalar-ve-aksesuarlar-cetirler', 'Зонты', 'Umbrellas'),
  ('kisi-geyimleri-cimerlik-geyimleri', 'Пляжная одежда', 'Swimwear'),
  ('qadin-geyimleri-cimerlik-geyimleri', 'Пляжная одежда', 'Swimwear'),
  ('ev-ve-metbex-isiqlandirma', 'Освещение', 'Lighting'),
  ('usaq-ve-korpe-velosiped-ve-samokat', 'Велосипеды и самокаты', 'Bikes & scooters'),
  ('ev-ve-metbex-dekor-mehsullari', 'Декор', 'Decor products'),
  ('qadin-geyimleri-hicab-geyimleri', 'Одежда для хиджаба', 'Hijab clothing'),
  ('kisi-geyimleri-is-geyimleri', 'Рабочая одежда', 'Workwear'),
  ('elektronika-qulaqliqlar', 'Наушники', 'Headphones'),
  ('qadin-geyimleri-hamile-geyimleri', 'Одежда для беременных', 'Maternity clothing'),
  ('elektronika-kamera-ve-fotoaparatlar', 'Камеры и фотоаппараты', 'Cameras & photo'),
  ('ev-ve-metbex-temizlik-vasiteleri', 'Средства для уборки', 'Cleaning supplies'),
  ('elektronika-smart-saatlar', 'Умные часы', 'Smart watches'),
  ('elektronika-oyun-konsollari', 'Игровые консоли', 'Game consoles'),
  ('elektronika-powerbanklar', 'Повербанки', 'Power banks'),
  ('elektronika-kabeller-ve-adapterler', 'Кабели и адаптеры', 'Cables & adapters')
)
update public.categories as category
set
  name_ru = case when nullif(btrim(category.name_ru), '') is null then translations.name_ru else category.name_ru end,
  name_en = case when nullif(btrim(category.name_en), '') is null then translations.name_en else category.name_en end
from translations
where category.slug = translations.slug
  and (nullif(btrim(category.name_ru), '') is null or nullif(btrim(category.name_en), '') is null);
